# Generated by Django 2.1.2 on 2018-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstOne', models.CharField(max_length=10)),
                ('firstTwo', models.IntegerField()),
            ],
        ),
    ]
