# Generated by Django 2.1.2 on 2018-10-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppName', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='firstOne',
            new_name='fieldOne',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='firstTwo',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='fieldTwo',
            field=models.IntegerField(default=0),
        ),
    ]
