# Generated by Django 2.1.2 on 2018-11-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181115_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faction',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
