# Generated by Django 2.1.2 on 2018-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
